image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - package

build:
  image: gradle:jdk14
  stage: build
  script:
    - gradle -x test build
  artifacts:
    paths:
      - build/libs/winllc-ra-server-1.0-SNAPSHOT.jar
      - build/resources/main/*.jks
      - build/resources/main/*.pfx

package:
  stage: package
  script:
    - docker build -t registry.gitlab.winllc-dev.com/root/pki-registration-authority .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.winllc-dev.com
    - docker push registry.gitlab.winllc-dev.com/root/pki-registration-authority