debug: false
app-keystore:
  location: /ssl/dogtag-ca-admin-with-chain.pfx
  password: P@ssW0rd
  type: PKCS12
win-ra:
  acme-server-url: http://winra.winllc-dev.com:8181
  acme-server-name: winllc
management:
  health:
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:mysql://database.winllc-dev.com/winpkira-dev
    driver-class-name: com.mysql.jdbc.Driver
    username: appuser
    password: P@ssW0rd
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.winllc-dev.com/auth/realms/dev
rest:
  security:
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      max-age: 3600
logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never
  port: 8080
  servlet:
    context-path: /
  #address: 192.168.1.13
  base-url: http://winra.winllc-dev.com:8080
  ssl:
    enabled: false
    trust-store: /ssl/trust.jk
    trust-store-password: password
keycloak-admin-interface:
  server-base-url: 'https://keycloak.winllc-dev.com/auth'
  realm: dev
  client-id: win-pki-ra-client
  client-secret: 4f6e55f4-1d4c-4f84-8564-0e2fd4194eea
  client-username: dave
  client-password: pass
  custom-client-scope: pki-app
authentication:
  jwt-required-audience: pki-ra-client-public
external-services:
  oidc:
    enabled-connection-names: oidc-keycloak
  identity:
    enabled-connection-names: identity-keycloak

policy-server:
  ldap-url: ldap://directory.winllc-dev.com:389
  ldap-username: cn=Directory Manager
  ldap-password: P@ssW0rd
  ldap-base-dn: dc=winllc-dev,dc=com

web-ui:
  server-base: http://winra.winllc-dev.com:3000
  uri-templates:
    account-created: /account/edit/{0}
permissions:
  available:
    - super_admin
    - add_domain
    - update_domain
    - delete_domain
    - add_account
    - update_account
    - delete_account
    - add_account_restriction
    - update_account_restriction
    - delete_account_restriction