package com.winllc.pki.ra.constants;

public enum AuditRecordType {
    CERTIFICATE_ISSUED,
    CERTIFICATE_REVOKED,
    SERVER_ENTRY_ADDED,
    SERVER_ENTRY_UPDATED,
    SERVER_ENTRY_REMOVED,
    ACCOUNT_ADDED,
    ACCOUNT_POCS_UPDATED,
    ACCOUNT_REMOVED
}
